# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-20 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc_demo_2017', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nvdimm',
            name='bw',
            field=models.IntegerField(default='x'),
        ),
        migrations.AlterField(
            model_name='nvdimm',
            name='iops',
            field=models.IntegerField(default='x'),
        ),
        migrations.AlterField(
            model_name='nvdimm',
            name='lat',
            field=models.IntegerField(default='x'),
        ),
    ]
